---
- hosts: FreshlyInstalledBoards
  remote_user: muhkuh
  become: yes
  become_user: root
  vars:
    ask_pass: True
    ansible_ssh_pass: muhkuh65536
  vars_prompt:
  - name: cfg_hostname
    prompt: 'Please enter the hostname of the new flash station'
    private: no
    when: cfg_hostname is undefined

  tasks:
  - name: disable unneeded hardware
    lineinfile:
      path: /boot/firmware/usercfg.txt
      state: present
      line: '{{ item }}'
    with_items:
      - 'dtoverlay=disable-wifi'
      - 'dtoverlay=disable-bt'
      - 'hdmi_blanking=2'
      - 'disable_splash=1'
      - 'boot_delay=0'

  - name: blacklist unwanted modules
    kernel_blacklist:
      blacklist_file: /etc/modprobe.d/raspi-blacklist.conf
      name: '{{ item }}'
      state: present
    with_items:
      - 'brcmfmac'
      - 'brcmutil'
      - 'bluetooth'
      - 'btsdio'

  - name: uninstall unwanted packets
    apt:
      name: landscape-common, pastebinit, plymouth, snapd, unattended-upgrades, cloud-init
      state: absent
      purge: yes

  - name: Disable unwanted services.
    systemd:
      name: '{{ item }}'
      enabled: no
      state: stopped
    with_items:
      - 'apt-daily.timer'
      - 'announce_ip.service'
      - 'wpa_supplicant.service'
      - 'accounts-daemon.service'

  - name: limit the journal
    ini_file:
      path: /etc/systemd/journald.conf
      section: Journal
      option: SystemMaxUse
      value: 128M
      create: no

  - name: Install the raspberry-ready-led
    unarchive:
      # Source: https://github.com/muhkuh-sys/org.muhkuh.tools-raspberry-ready-led/releases/download/v0.0.1/raspberry-ready-led-0.0.1-ubuntu-20.04_arm64.tar.gz
      src: data/raspberry-ready-led-0.0.1-ubuntu-20.04_arm64.tar.gz
      dest: /opt/
  - name: Install the raspberry-ready-led service file
    copy:
      src: /opt/raspberry-ready-led-0.0.1/systemd/ready_led.service
      dest: /lib/systemd/system/
      remote_src: yes
  - name: Enable the raspberry-ready-led service
    systemd:
      name: ready_led.service
      enabled: yes
      masked: no

  - name: install the eth-kickstart
    unarchive:
      # Source: https://github.com/muhkuh-sys/org.muhkuh.tools-eth_kick_start/releases/download/v0.0.1/eth_kick_start_netx4000-0.0.1-ubuntu-20.04_arm64.tar.gz
      src: data/eth_kick_start_netx4000-0.0.1-ubuntu-20.04_arm64.tar.gz
      dest: /opt/
  - name: install the eth-kickstart service file
    copy:
      src: data/lib/systemd/system/eth_kickstart.service
      dest: /lib/systemd/system/
  - name: Enable the eth-kickstart service
    systemd:
      name: eth_kickstart.service
      enabled: yes
      masked: no

  - name: install the TFTP server
    apt:
      name: tftpd-hpa
      state: present
  - name: Set the TFTP directory
    ini_file:
      path: /etc/default/tftpd-hpa
      section: null
      option: TFTP_DIRECTORY
      value: '"/media/data"'
      create: no
      no_extra_spaces: yes
  - name: Create the TFTP directory
    file:
      path: /media/data
      state: directory

  - name: install the DHCP server
    apt:
      name: isc-dhcp-server
      state: present
  - name: install the DHCP configuration
    copy:
      src: data/etc/dhcp/dhcpd.conf
      dest: /etc/dhcp/
      force: yes

  - name: install the network configuration
    copy:
      src: data/etc/netplan/50-cloud-init.yaml
      dest: /etc/netplan/
      force: yes
  - name: prevent cloud network configuration
    copy:
      src: data/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
      dest: /etc/cloud/cloud.cfg.d/
      force: yes

  - name: mount the memorystick at /media/data
    lineinfile:
      path: /etc/fstab
      state: present
      line: '/dev/sda1 /media/data vfat auto,nodev,noexec,nosuid,ro 0 0'

  - name: set the new hostname
    hostname:
      name: "{{ cfg_hostname }}"

  - name: Set the filesystem to read-only
    lineinfile:
      path: /etc/overlayroot.local.conf
      state: present
      line: '{{ item }}'
    with_items:
      - 'overlayroot_cfgdisk=LABEL=OROOTCFG'
      - 'overlayroot="tmpfs:recurse=0"'

  - name: Poweroff
    shell:
      cmd: poweroff
